{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "code-maker",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-maker-2.0.0.jar",
          "url": "code-maker-2.0.0.jar",
          "size": 32555,
          "sha512": "d429c5197de1babb2a20538dc3ee577600613cb3b1e20ad985c2785df77e2e63e7b1700f2570aa07089a15f47b09a97882180d3725c7e991f9b5d43f98f29afb",
          "sha256": "b6b3c8f35293b3cb7758e03f86d608af5d896c22214eed8c23cbfc4114b76811",
          "sha1": "bc7ec40e11a8dc0c6eae398b7644657aba67ac9b",
          "md5": "41414308af6b346ae4ac47eb93103d15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-generator",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker"
        },
        {
          "group": "com.jmc",
          "module": "jmc-utils",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "code-maker-2.0.0.jar",
          "url": "code-maker-2.0.0.jar",
          "size": 32555,
          "sha512": "d429c5197de1babb2a20538dc3ee577600613cb3b1e20ad985c2785df77e2e63e7b1700f2570aa07089a15f47b09a97882180d3725c7e991f9b5d43f98f29afb",
          "sha256": "b6b3c8f35293b3cb7758e03f86d608af5d896c22214eed8c23cbfc4114b76811",
          "sha1": "bc7ec40e11a8dc0c6eae398b7644657aba67ac9b",
          "md5": "41414308af6b346ae4ac47eb93103d15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-sources.jar",
          "url": "code-maker-2.0.0-sources.jar",
          "size": 19542,
          "sha512": "77ea7ef18fb6922faafb157c468045495ad25a23b02e6a6e30162a2d022eca529e3a3c0c30d0a5b3a22f585a27a5965d0b0e22dd289c236a3d46041df021702d",
          "sha256": "2e976855af7d8ff3f179598c0137f13e7a6c9330c01d4118d0f70b12da8a752f",
          "sha1": "7a6b6c8b97e1b368f3985efa8dcc3b238df953e5",
          "md5": "883292c51182d480ab618d168f123035"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-javadoc.jar",
          "url": "code-maker-2.0.0-javadoc.jar",
          "size": 158654,
          "sha512": "306c06e0b471388c6f6a16098adfa44edb5587870f324d2bb327758547e02f843160bf4627b172786ab822be9c18d03e8b3f024db83ea9d4e948b89baaedb7e4",
          "sha256": "35fe597e4c2998d42207b51639170e0b3d362e7ed60526975e4897d83c3139c2",
          "sha1": "ac2bb8967bf98a22c0917d9456e610cdcc17ff63",
          "md5": "b8fdf6f6ed38c86f61536a5f2adf1a79"
        }
      ]
    }
  ]
}
