{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "code-maker",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-plain.jar",
          "url": "code-maker-2.0.0-plain.jar",
          "size": 32607,
          "sha512": "eb9db6fb936d57adeb5336009670bfee676d4906d18f8363b9c9fe20d77bd3847db0fd1ae1b0e600636bef5fab967eab25213b6821d979594b22076a126835f6",
          "sha256": "16702d91ea0adf3613683029419f3635f246e2aea5d512a8df8d7fd5e78477fb",
          "sha1": "316827f26d8f43768eed1a0efb5f9513865c7b4a",
          "md5": "bafa3b7dd372130c7850bb143fa3ad92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-generator",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker"
        },
        {
          "group": "com.jmc",
          "module": "jmc-utils",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "code-maker-2.0.0-plain.jar",
          "url": "code-maker-2.0.0-plain.jar",
          "size": 32607,
          "sha512": "eb9db6fb936d57adeb5336009670bfee676d4906d18f8363b9c9fe20d77bd3847db0fd1ae1b0e600636bef5fab967eab25213b6821d979594b22076a126835f6",
          "sha256": "16702d91ea0adf3613683029419f3635f246e2aea5d512a8df8d7fd5e78477fb",
          "sha1": "316827f26d8f43768eed1a0efb5f9513865c7b4a",
          "md5": "bafa3b7dd372130c7850bb143fa3ad92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-sources.jar",
          "url": "code-maker-2.0.0-sources.jar",
          "size": 19602,
          "sha512": "31d26a082e19ec7430696017465648574b79062f3f69c9dcea260af32de9138f339c981fced05cdc50beece5fc0ab5e7dd1d2b1e04d7b3623da90767b04a3319",
          "sha256": "589821a6e3f7738ff1e581a57431d8de9104d1cd908bc5ff9798c303e6e04d6f",
          "sha1": "7d96b53f6d249dc9d7c7385813a12b5bc82d5a66",
          "md5": "1d7bd16559f0abaf420bdb36841859b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-javadoc.jar",
          "url": "code-maker-2.0.0-javadoc.jar",
          "size": 158654,
          "sha512": "65cee9ffd8866cffa12327ace837cee326e97a0515704b34d87c7ee5191e27bd934bf7b152569bd81d8eb5350e925e712a5e494eecd7cce8bd89259f7666bd2d",
          "sha256": "abfd715bea87385f1da5f538db75ff626284b39b94750d673b01ae25936bfd35",
          "sha1": "3e4550809bc33f73311333787f311fe217682c6b",
          "md5": "b51784eb3d70cea8ba9eb233e38fce89"
        }
      ]
    }
  ]
}
