{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jmc",
    "module": "code-maker",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "code-maker-2.0.0.jar",
          "url": "code-maker-2.0.0.jar",
          "size": 32560,
          "sha512": "a55d65ded7df44ba1e2604823f73b1e96a4f4cbbd95458b637b317a22c038ad1240831520e1408eb857aa03feb3261597c9d519c31145bbcf81dc339b470c146",
          "sha256": "0768308f810989b1c521d347d99213984daa1f0e90514b0223077d8ae0d58ebd",
          "sha1": "c00da2bb10720d184ade9fd88013007ac72b3aef",
          "md5": "6b7504721a7cacaeb0ec42e21af289b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus-generator",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker"
        },
        {
          "group": "com.jmc",
          "module": "jmc-utils",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "code-maker-2.0.0.jar",
          "url": "code-maker-2.0.0.jar",
          "size": 32560,
          "sha512": "a55d65ded7df44ba1e2604823f73b1e96a4f4cbbd95458b637b317a22c038ad1240831520e1408eb857aa03feb3261597c9d519c31145bbcf81dc339b470c146",
          "sha256": "0768308f810989b1c521d347d99213984daa1f0e90514b0223077d8ae0d58ebd",
          "sha1": "c00da2bb10720d184ade9fd88013007ac72b3aef",
          "md5": "6b7504721a7cacaeb0ec42e21af289b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-sources.jar",
          "url": "code-maker-2.0.0-sources.jar",
          "size": 19547,
          "sha512": "0e38aaa1ed541ff2d48e67c6d1b6dd3e2a5b33b3c524e535753890bbaa9a8dbc4ac4b2e4605547469a97c6f657b7d0604fb642b1d6b70a92cd9c35495cb084b3",
          "sha256": "f234efdfe988e93213643d7ccbfd19f8bf36286f3c2cb98be6c65ba044878554",
          "sha1": "81110ab6e21f0c8ae61fcf455d3ca060a2f78f42",
          "md5": "d0d88a5468590c94ea3a6fbd743221a0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "code-maker-2.0.0-javadoc.jar",
          "url": "code-maker-2.0.0-javadoc.jar",
          "size": 158654,
          "sha512": "306c06e0b471388c6f6a16098adfa44edb5587870f324d2bb327758547e02f843160bf4627b172786ab822be9c18d03e8b3f024db83ea9d4e948b89baaedb7e4",
          "sha256": "35fe597e4c2998d42207b51639170e0b3d362e7ed60526975e4897d83c3139c2",
          "sha1": "ac2bb8967bf98a22c0917d9456e610cdcc17ff63",
          "md5": "b8fdf6f6ed38c86f61536a5f2adf1a79"
        }
      ]
    }
  ]
}
